# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_name', models.CharField(max_length=128)),
                ('file_date', models.DateField()),
                ('is_incumbent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('election_type', models.CharField(choices=[('F', 'Federal'), ('S', 'State'), ('CO', 'County'), ('C', 'City')], max_length=2)),
                ('is_statewide', models.BooleanField()),
                ('name', models.TextField(blank=True)),
                ('results_uri', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_id', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('full_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('biography', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('party_affiliation', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('voters_edge_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('filer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ballot.Filer')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ballot.State'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot.Person'),
        ),
    ]
